version: '3'

services:
    redis:
        image: redis:6.2
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock      
        ports:
          - 6379:6379 
    app:
        build: ./
        ports:
          - 8080:8080
        depends_on:
          - redis
          